image: node:12.18-alpine # can be upgraded, depending on your node version used

pages:
  stage: deploy
  script:
    - yarn install
    - yarn build
    - rm -rf public
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - master
